# This file was generated by GoReleaser. DO NOT EDIT.
class AltiCli < Formula
  desc "Command line interface for altizure.com, with fast and robust uploads."
  homepage "https://github.com/altizure/alti-cli"
  version "1.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/altizure/alti-cli/releases/download/v1.1.1/alti-cli_1.1.1_Darwin_x86_64.tar.gz"
    sha256 "5234fbc524558fec389b4f1b0bec91194b99e16ace65f979636920d287c625e0"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/altizure/alti-cli/releases/download/v1.1.1/alti-cli_1.1.1_Linux_x86_64.tar.gz"
      sha256 "94e2dc5e903bd521d932663b52feec448441bc3cf3fd17013bda32bf75f6dcdd"
    end
  end

  def install
    bin.install "alti-cli"
  end

  test do
    system "#{bin}/alti-cli version"
  end
end
